export const ErrorCodes = {
  CLIENT_HAS_DEALS: "CLIENT_HAS_DEALS",
  BROKER_CONTRACT_EXPIRED: "BROKER_CONTRACT_EXPIRED",
  TERMINAL_CONFIRMATION_REQUIRED: "TERMINAL_CONFIRMATION_REQUIRED",
  TERMINAL_STAGE_LOCKED: "TERMINAL_STAGE_LOCKED",
  NOT_DEAL_OWNER: "NOT_DEAL_OWNER",
  CANNOT_DELETE_SELF: "CANNOT_DELETE_SELF",
} as const;
export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
